#include "op_tree.h"

#include "common.h"

// These eight nodes are disambiguating nop from 255 surrounding reserved ops.
const PROGMEM op_node op_node_000w={0x0001u, {
	LEAF(STRING_NOP,      OP_CONST_CHR),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
}};

const PROGMEM op_node op_node_000z={0x0002u, {
	NODE(op_node_000w),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
}};

const PROGMEM op_node op_node_000y={0x0004u, {
	NODE(op_node_000z),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
}};

const PROGMEM op_node op_node_000x={0x0008u, {
	NODE(op_node_000y),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
}};

const PROGMEM op_node op_node_00ww={0x0010u, {
	NODE(op_node_000x),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
}};

const PROGMEM op_node op_node_00zz={0x0020u, {
	NODE(op_node_00ww),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
}};

const PROGMEM op_node op_node_00yy={0x0040u, {
	NODE(op_node_00zz),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
}};

const PROGMEM op_node op_node_00xx={0x0080u, {
	NODE(op_node_00yy),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
}};

const PROGMEM op_node op_node_03xx={0x0088u, {
	LEAF(STRING_MULSU,  OP_D3_R3_CHR), 
	LEAF(STRING_FMUL,   OP_D3_R3_CHR), 
	LEAF(STRING_FMULS,  OP_D3_R3_CHR), 
	LEAF(STRING_FMULSU, OP_D3_R3_CHR), 
}};

const PROGMEM op_node op_node_0yyy={0x0300u, {
	NODE(op_node_00xx), 
	LEAF(STRING_MOVW, OP_D4_R4_CHR),
	LEAF(STRING_MULS, OP_D4_R4_CHR),
	NODE(op_node_03xx), 
}};

const PROGMEM op_node op_node_0xxx={0x0c00u, {
	NODE(op_node_0yyy), 
	LEAF(STRING_CPC, OP_RD_D4_R4_CHR),
	LEAF(STRING_SBC, OP_RD_D4_R4_CHR),
	LEAF(STRING_ADD, OP_RD_D4_R4_CHR),
}};

const PROGMEM op_node op_node_1xxx={0x0c00u, {
	LEAF(STRING_CPSE, OP_RD_D4_R4_CHR),
	LEAF(STRING_CP,   OP_RD_D4_R4_CHR),
	LEAF(STRING_SUB,  OP_RD_D4_R4_CHR),
	LEAF(STRING_ADC,  OP_RD_D4_R4_CHR),
}};

const PROGMEM op_node op_node_2xxx={0x0c00u, {
	LEAF(STRING_AND, OP_RD_D4_R4_CHR),
	LEAF(STRING_EOR, OP_RD_D4_R4_CHR),
	LEAF(STRING_OR,  OP_RD_D4_R4_CHR),
	LEAF(STRING_MOV, OP_RD_D4_R4_CHR),
}};

const PROGMEM op_node op_node_8a={0x0200u, {
	LEAF(STRING_LD, OP_Q_R5_CHR),
	LEAF(STRING_ST, OP_Q_R5_CHR),
}};

const PROGMEM op_node op_node_bxxx={0x0800u, {
	LEAF(STRING_IN,  OP_IO_R5_CHR),
	LEAF(STRING_OUT, OP_IO_R5_CHR),
}};

const PROGMEM op_node op_node_f0={0x0c07u, {
	LEAF(STRING_BRCS, OP_K7_CHR),
	LEAF(STRING_BREQ, OP_K7_CHR),
	LEAF(STRING_BRMI, OP_K7_CHR),
	LEAF(STRING_BRVS, OP_K7_CHR),
	LEAF(STRING_BRLT, OP_K7_CHR),
	LEAF(STRING_BRHS, OP_K7_CHR),
	LEAF(STRING_BRTS, OP_K7_CHR),
	LEAF(STRING_BRIE, OP_K7_CHR),
	LEAF(STRING_BRCC, OP_K7_CHR),
	LEAF(STRING_BRNE, OP_K7_CHR),
	LEAF(STRING_BRPL, OP_K7_CHR),
	LEAF(STRING_BRVC, OP_K7_CHR),
	LEAF(STRING_BRGE, OP_K7_CHR),
	LEAF(STRING_BRHC, OP_K7_CHR),
	LEAF(STRING_BRTC, OP_K7_CHR),
	LEAF(STRING_BRID, OP_K7_CHR),
}};

const PROGMEM op_node op_node_f8_real={0x0600u, {
	LEAF(STRING_BLD,  OP_R5_B_CHR),
	LEAF(STRING_BST,  OP_R5_B_CHR),
	LEAF(STRING_SBRC, OP_R5_B_CHR),
	LEAF(STRING_SBRS, OP_R5_B_CHR),
}};

const PROGMEM op_node op_node_f8={0x0008u, {
	NODE(op_node_f8_real),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
}};

const PROGMEM op_node op_node_fxxx={0x0800u, {
	NODE(op_node_f0),
	NODE(op_node_f8),
}};

const PROGMEM op_node op_node_misc1={0x000f, {
	LEAF(STRING_LDS,  OP_R5_K16_CHR),
	LEAF(STRING_LD,   OP_R5_Y_P_CHR),
	LEAF(STRING_LD,   OP_R5_Y_P_CHR),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
	LEAF(STRING_LPM,  OP_R5_LPM_CHR),
	LEAF(STRING_LPM,  OP_R5_LPM_CHR),
	LEAF(STRING_ELPM, OP_R5_LPM_CHR),
	LEAF(STRING_ELPM, OP_R5_LPM_CHR),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
	LEAF(STRING_LD,   OP_R5_Y_P_CHR),
	LEAF(STRING_LD,   OP_R5_Y_P_CHR),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
	LEAF(STRING_LD,   OP_R5_Y_P_CHR),
	LEAF(STRING_LD,   OP_R5_Y_P_CHR),
	LEAF(STRING_LD,   OP_R5_Y_P_CHR),
	LEAF(STRING_POP,  OP_R5_CHR),
}};

const PROGMEM op_node op_node_misc2={0x000f, {
	LEAF(STRING_STS,  OP_R5_K16_STS_CHR),
	LEAF(STRING_ST,   OP_R5_Y_P_ST_CHR),
	LEAF(STRING_ST,   OP_R5_Y_P_ST_CHR),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
	LEAF(STRING_XCH_, OP_R5_CHR),
	LEAF(STRING_LAS_, OP_R5_CHR),
	LEAF(STRING_LAC_, OP_R5_CHR),
	LEAF(STRING_LAT_, OP_R5_CHR),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
	LEAF(STRING_ST,   OP_R5_Y_P_ST_CHR),
	LEAF(STRING_ST,   OP_R5_Y_P_ST_CHR),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
	LEAF(STRING_ST,   OP_R5_Y_P_ST_CHR),
	LEAF(STRING_ST,   OP_R5_Y_P_ST_CHR),
	LEAF(STRING_ST,   OP_R5_Y_P_ST_CHR),
	LEAF(STRING_PUSH, OP_R5_CHR),
}};

const PROGMEM op_node op_node_misc_9x8x={0x01f0, {
	LEAF(STRING_SEC,  OP_CONST_CHR),
	LEAF(STRING_SEZ,  OP_CONST_CHR),
	LEAF(STRING_SEN,  OP_CONST_CHR),
	LEAF(STRING_SEV,  OP_CONST_CHR),
	LEAF(STRING_SES,  OP_CONST_CHR),
	LEAF(STRING_SEH,  OP_CONST_CHR),
	LEAF(STRING_SET,  OP_CONST_CHR),
	LEAF(STRING_SEI,  OP_CONST_CHR),
	LEAF(STRING_CLC,  OP_CONST_CHR),
	LEAF(STRING_CLZ,  OP_CONST_CHR),
	LEAF(STRING_CLN,  OP_CONST_CHR),
	LEAF(STRING_CLV,  OP_CONST_CHR),
	LEAF(STRING_CLS,  OP_CONST_CHR),
	LEAF(STRING_CLH,  OP_CONST_CHR),
	LEAF(STRING_CLT,  OP_CONST_CHR),
	LEAF(STRING_CLI,  OP_CONST_CHR),
	LEAF(STRING_RET,  OP_CONST_CHR),
	LEAF(STRING_RETI, OP_CONST_CHR),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
	LEAF(STRING_SLEEP, OP_CONST_CHR),
	LEAF(STRING_BREAK, OP_CONST_CHR),
	LEAF(STRING_WDR,   OP_CONST_CHR),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
	LEAF(STRING_LPM,  OP_CONST_CHR),
	LEAF(STRING_ELPM, OP_CONST_CHR),
	LEAF(STRING_SPM,  OP_CONST_CHR),
	LEAF(STRING_SPM_, OP_CONST_CHR),
}};

const PROGMEM op_node op_node_misc_9x9x_c={0x0110, {
	LEAF(STRING_IJMP, OP_CONST_CHR),
	LEAF(STRING_EIJMP, OP_CONST_CHR),
	LEAF(STRING_ICALL, OP_CONST_CHR),
	LEAF(STRING_EICALL, OP_CONST_CHR),
}};

const PROGMEM op_node op_node_misc_9x9x_b={0x0020, {
	NODE(op_node_misc_9x9x_c),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
}};

const PROGMEM op_node op_node_misc_9x9x_a={0x0040, {
	NODE(op_node_misc_9x9x_b),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
}};

const PROGMEM op_node op_node_misc_9x9x={0x0080, {
	NODE(op_node_misc_9x9x_a),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
}};

const PROGMEM op_node op_node_misc_9xbx={0x0100, {
	LEAF(STRING_DES, OP_K4_CHR),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
}};

const PROGMEM op_node op_node_misc3={0x000f, {
	LEAF(STRING_COM,  OP_R5_CHR),
	LEAF(STRING_NEG,  OP_R5_CHR),
	LEAF(STRING_SWAP, OP_R5_CHR),
	LEAF(STRING_INC,  OP_R5_CHR),
	LEAF(STRING_RESERVED, OP_CONST_CHR),
	LEAF(STRING_ASR,  OP_R5_CHR),
	LEAF(STRING_LSR,  OP_R5_CHR),
	LEAF(STRING_ROR,  OP_R5_CHR),
	NODE(op_node_misc_9x8x),
	NODE(op_node_misc_9x9x),
	LEAF(STRING_DEC,  OP_R5_CHR),
	NODE(op_node_misc_9xbx),
	LEAF(STRING_JMP,  OP_K22_CHR),
	LEAF(STRING_JMP,  OP_K22_CHR),
	LEAF(STRING_CALL, OP_K22_CHR),
	LEAF(STRING_CALL, OP_K22_CHR),
}};

const PROGMEM op_node op_node_adiw_sbiw={0x0100, {
	LEAF(STRING_ADIW, OP_K6_R2_CHR),
	LEAF(STRING_SBIW, OP_K6_R2_CHR),
}};

const PROGMEM op_node op_node_cbi_sbic={0x0100, {
	LEAF(STRING_CBI,  OP_IO_B_CHR),
	LEAF(STRING_SBIC, OP_IO_B_CHR),
}};

const PROGMEM op_node op_node_sbi_sbis={0x0100, {
	LEAF(STRING_SBI,  OP_IO_B_CHR),
	LEAF(STRING_SBIS, OP_IO_B_CHR),
}};

const PROGMEM op_node op_node_9xxx={0x0e00u, {
	NODE(op_node_misc1),
	NODE(op_node_misc2),
	NODE(op_node_misc3),
	NODE(op_node_adiw_sbiw),
	NODE(op_node_cbi_sbic),
	NODE(op_node_sbi_sbis),
	LEAF(STRING_MUL, OP_RD_D4_R4_CHR),
	LEAF(STRING_MUL, OP_RD_D4_R4_CHR),
}};

const PROGMEM op_node op_node_root={0xf000u, { 
	NODE(op_node_0xxx),
	NODE(op_node_1xxx),
	NODE(op_node_2xxx),
	LEAF(STRING_CPI,  OP_K8_R4_CHR), 
	LEAF(STRING_SBCI, OP_K8_R4_CHR), 
	LEAF(STRING_SUBI, OP_K8_R4_CHR), 
	LEAF(STRING_ORI,  OP_K8_R4_CHR), 
	LEAF(STRING_ANDI, OP_K8_R4_CHR), 
	NODE(op_node_8a),
	NODE(op_node_9xxx),
	NODE(op_node_8a),
	NODE(op_node_bxxx),
	LEAF(STRING_RJMP, OP_K12_CHR), 
	LEAF(STRING_RCALL,OP_K12_CHR), 
	LEAF(STRING_LDI,  OP_K8_R4_CHR), 
	NODE(op_node_fxxx),
}};
